name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Add SSH Host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 194.233.83.149 >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -v -o StrictHostKeyChecking=no root@194.233.83.149 '
            cd /home/eg-hotel-fe &&
            git pull origin main &&
            docker compose -f compose.prod.yaml up -d --build
          '
